language: php

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - "7.2"

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

# Run script
script:
  - ./vendor/bin/phpunit ./src/DinnerBundle/Tests
  - ./vendor/bin/infection --min-covered-msi=100
