app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

dinner:
    resource: "@DinnerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
